# Generated by Django 6.0.8 on 2026-10-06 07:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(default='Custom Item', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('hsn_sac', models.CharField(blank=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Draft', max_length=30)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('transporter_name', models.CharField(blank=True, max_length=180)),
                ('transporter_id', models.CharField(blank=True, max_length=50)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('estimate', 'Estimate')], default='invoice', max_length=20)),
                ('invoice_type', models.CharField(default='regular', max_length=20)),
                ('status', models.CharField(default='Draft', max_length=30)),
                ('date', models.DateField()),
                ('seller_snapshot', models.JSONField(blank=True, default=dict)),
                ('customer_snapshot', models.JSONField(blank=True, default=dict)),
                ('vehicle_snapshot', models.JSONField(blank=True, default=dict)),
                ('transport', models.JSONField(blank=True, default=dict)),
                ('tax_mode', models.CharField(default='none', max_length=20)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('payment_type', models.CharField(blank=True, max_length=30)),
                ('terms_conditions', models.TextField(blank=True)),
                ('staff_name', models.CharField(blank=True, max_length=160)),
                ('source_job_id', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
