import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def backfill_compensation_plans(apps,schema_editor):
    SalaryStructure=apps.get_model("payroll","SalaryStructure")
    EmployeeCompensationPlan=apps.get_model("payroll","EmployeeCompensationPlan")

    for structure in SalaryStructure.objects.select_related("employee").all():
        rule=structure.incentive_rule or {}
        basis=str(rule.get("salaryBasis") or "Fixed Monthly").lower()
        payment_type={
            "hourly":"hourly",
            "daily":"daily",
            "commission only":"commission",
            "fixed monthly":"monthly",
        }.get(basis,"monthly")

        EmployeeCompensationPlan.objects.get_or_create(
            company_id=structure.company_id,
            employee_id=structure.employee_id,
            effective_from=structure.effective_from,
            defaults={
                "branch_id":structure.branch_id,
                "payment_type":payment_type,
                "base_salary":structure.basic,
                "daily_wage_rate":Decimal(str(rule.get("dailyRate") or 0)),
                "hourly_wage_rate":Decimal(str(rule.get("hourlyRate") or 0)),
                "commission_type":"percentage" if payment_type=="commission" else "none",
                "commission_percentage":Decimal(str(rule.get("commissionPercentage") or 0)),
                "commission_fixed_amount":Decimal("0"),
                "eligible_revenue_basis":"labour_revenue",
                "overtime_eligible":True,
                "incentive_eligible":True,
                "bonus_rules":{"fixedAmount":rule.get("fixed",0)},
                "applicable_deductions":[
                    {
                        "code":"LEGACY",
                        "name":"Legacy deductions",
                        "amount":float(structure.deductions),
                    }
                ] if structure.deductions else [],
                "payment_frequency":"monthly",
                "approval_status":"Approved",
                "is_active":True,
                "notes":"Backfilled from legacy salary structure.",
            },
        )


class Migration(migrations.Migration):

    dependencies=[
        ("jobs","0003_customer_feedback"),
        ("payroll","0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations=[
        migrations.CreateModel(
            name="PayrollPolicy",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("name",models.CharField(default="Default",max_length=120)),
                ("default_payment_type",models.CharField(choices=[
                    ("monthly","Fixed Monthly Salary"),
                    ("daily","Daily Wage"),
                    ("hourly","Hourly Wage"),
                    ("commission","Commission Only"),
                    ("monthly_commission","Monthly Salary + Commission"),
                    ("daily_commission","Daily Wage + Commission"),
                    ("hourly_commission","Hourly Wage + Commission"),
                    ("salary_incentive","Fixed Salary + Job Incentive"),
                    ("hybrid","Custom Hybrid Compensation"),
                ],default="monthly",max_length=40)),
                ("payroll_cycle",models.CharField(default="monthly",max_length=30)),
                ("working_day_calculation",models.CharField(default="attendance",max_length=40)),
                ("overtime_rules",models.JSONField(blank=True,default=dict)),
                ("commission_rules",models.JSONField(blank=True,default=dict)),
                ("job_incentive_rules",models.JSONField(blank=True,default=dict)),
                ("approval_workflow",models.JSONField(blank=True,default=dict)),
                ("payment_methods",models.JSONField(blank=True,default=list)),
                ("unpaid_leave_policy",models.JSONField(blank=True,default=dict)),
                ("is_default",models.BooleanField(default=True)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
            ],
            options={"ordering":["name"]},
        ),
        migrations.CreateModel(
            name="EmployeeCompensationPlan",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("payment_type",models.CharField(choices=[
                    ("monthly","Fixed Monthly Salary"),
                    ("daily","Daily Wage"),
                    ("hourly","Hourly Wage"),
                    ("commission","Commission Only"),
                    ("monthly_commission","Monthly Salary + Commission"),
                    ("daily_commission","Daily Wage + Commission"),
                    ("hourly_commission","Hourly Wage + Commission"),
                    ("salary_incentive","Fixed Salary + Job Incentive"),
                    ("hybrid","Custom Hybrid Compensation"),
                ],default="monthly",max_length=40)),
                ("base_salary",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("daily_wage_rate",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("hourly_wage_rate",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("commission_type",models.CharField(choices=[("none","None"),("percentage","Percentage"),("fixed","Fixed Amount")],default="none",max_length=20)),
                ("commission_percentage",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=7)),
                ("commission_fixed_amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("eligible_revenue_basis",models.CharField(choices=[("labour_revenue","Labour Revenue"),("service_revenue","Service Revenue"),("job_card","Job Card Commission"),("custom","Custom Eligible Revenue")],default="labour_revenue",max_length=30)),
                ("overtime_eligible",models.BooleanField(default=True)),
                ("incentive_eligible",models.BooleanField(default=True)),
                ("bonus_rules",models.JSONField(blank=True,default=dict)),
                ("applicable_deductions",models.JSONField(blank=True,default=list)),
                ("effective_from",models.DateField()),
                ("effective_to",models.DateField(blank=True,null=True)),
                ("payment_frequency",models.CharField(default="monthly",max_length=30)),
                ("approval_status",models.CharField(default="Approved",max_length=30)),
                ("is_active",models.BooleanField(default=True)),
                ("notes",models.TextField(blank=True)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_compensation_plans",to=settings.AUTH_USER_MODEL)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="compensation_plans",to="employees.employee")),
            ],
            options={"ordering":["employee","-effective_from","-created_at"]},
        ),
        migrations.CreateModel(
            name="CompensationComponent",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("code",models.CharField(max_length=60)),
                ("name",models.CharField(max_length=120)),
                ("kind",models.CharField(choices=[("earning","Earning"),("deduction","Deduction")],default="earning",max_length=20)),
                ("calculation_type",models.CharField(choices=[("fixed","Fixed"),("percent","Percent"),("per_day","Per Day"),("per_hour","Per Hour")],default="fixed",max_length=20)),
                ("amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("percentage",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=7)),
                ("revenue_basis",models.CharField(blank=True,max_length=30)),
                ("taxable",models.BooleanField(default=True)),
                ("is_active",models.BooleanField(default=True)),
                ("metadata",models.JSONField(blank=True,default=dict)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("plan",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="components",to="payroll.employeecompensationplan")),
            ],
            options={"ordering":["kind","name"]},
        ),
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("name",models.CharField(default="Default Commission",max_length=120)),
                ("commission_type",models.CharField(choices=[("none","None"),("percentage","Percentage"),("fixed","Fixed Amount")],default="percentage",max_length=20)),
                ("revenue_basis",models.CharField(choices=[("labour_revenue","Labour Revenue"),("service_revenue","Service Revenue"),("job_card","Job Card Commission"),("custom","Custom Eligible Revenue")],default="labour_revenue",max_length=30)),
                ("percentage",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=7)),
                ("fixed_amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("minimum_revenue",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("allocation_percent",models.DecimalField(decimal_places=4,default=Decimal("100"),max_digits=7)),
                ("effective_from",models.DateField()),
                ("effective_to",models.DateField(blank=True,null=True)),
                ("is_active",models.BooleanField(default=True)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="commission_rules",to="employees.employee")),
                ("plan",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="commission_rules",to="payroll.employeecompensationplan")),
            ],
            options={"ordering":["employee","-effective_from"]},
        ),
        migrations.CreateModel(
            name="JobCardEmployeeAssignment",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("role",models.CharField(blank=True,max_length=80)),
                ("assigned_at",models.DateTimeField(auto_now_add=True)),
                ("completed_at",models.DateTimeField(blank=True,null=True)),
                ("approved_work_minutes",models.PositiveIntegerField(default=0)),
                ("eligible_labour_revenue",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("eligible_service_revenue",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("commission_allocation_percent",models.DecimalField(decimal_places=4,default=Decimal("100"),max_digits=7)),
                ("status",models.CharField(default="Assigned",max_length=30)),
                ("metadata",models.JSONField(blank=True,default=dict)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="job_assignments",to="employees.employee")),
                ("job",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="employee_assignments",to="jobs.job")),
            ],
            options={"ordering":["-assigned_at"]},
        ),
        migrations.CreateModel(
            name="EmployeeWorkLog",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("work_date",models.DateField()),
                ("minutes",models.PositiveIntegerField(default=0)),
                ("labour_revenue",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("service_revenue",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("status",models.CharField(default="Pending",max_length=30)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("notes",models.TextField(blank=True)),
                ("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_employee_work_logs",to=settings.AUTH_USER_MODEL)),
                ("assignment",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="work_logs",to="payroll.jobcardemployeeassignment")),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="work_logs",to="employees.employee")),
                ("job",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="employee_work_logs",to="jobs.job")),
            ],
            options={"ordering":["-work_date","-created_at"]},
        ),
        migrations.CreateModel(
            name="EmployeeCommission",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("payroll_year",models.PositiveSmallIntegerField()),
                ("payroll_month",models.PositiveSmallIntegerField()),
                ("revenue_basis",models.CharField(default="labour_revenue",max_length=30)),
                ("eligible_base",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("commission_type",models.CharField(default="percentage",max_length=20)),
                ("rate",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=7)),
                ("fixed_amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("source_key",models.CharField(max_length=180)),
                ("status",models.CharField(default="Pending",max_length=30)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("metadata",models.JSONField(blank=True,default=dict)),
                ("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_employee_commissions",to=settings.AUTH_USER_MODEL)),
                ("assignment",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commissions",to="payroll.jobcardemployeeassignment")),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="generated_commissions",to="employees.employee")),
                ("job",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="employee_commissions",to="jobs.job")),
                ("plan",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="generated_commissions",to="payroll.employeecompensationplan")),
            ],
            options={"ordering":["-payroll_year","-payroll_month","employee"]},
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("month",models.PositiveSmallIntegerField()),
                ("year",models.PositiveSmallIntegerField()),
                ("status",models.CharField(default="Open",max_length=30)),
                ("starts_on",models.DateField()),
                ("ends_on",models.DateField()),
                ("locked_at",models.DateTimeField(blank=True,null=True)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("locked_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="locked_payroll_periods",to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-year","-month"]},
        ),
        migrations.RemoveConstraint(
            model_name="payrollrun",
            name="unique_payroll_period_per_company",
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="approval_status",
            field=models.CharField(default="Draft",max_length=30),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="approved_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="approved_by",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_payroll_runs",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="calculation_version",
            field=models.CharField(default="flex-v1",max_length=30),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="locked_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="metadata",
            field=models.JSONField(blank=True,default=dict),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="period",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="runs",to="payroll.payrollperiod"),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="processed_by",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="processed_payroll_runs",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="payslip",
            name="adjustment_amount",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="bonus_amount",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="calculation_snapshot",
            field=models.JSONField(blank=True,default=dict),
        ),
        migrations.AddField(
            model_name="payslip",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="compensation_plan",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="payslips",to="payroll.employeecompensationplan"),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payable_days",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=6),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payable_hours",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=9),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payment_type",
            field=models.CharField(blank=True,max_length=40),
        ),
        migrations.AddField(
            model_name="payslip",
            name="unpaid_leave_days",
            field=models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=6),
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("kind",models.CharField(default="earning",max_length=20)),
                ("code",models.CharField(max_length=60)),
                ("description",models.CharField(max_length=180)),
                ("quantity",models.DecimalField(decimal_places=4,default=Decimal("1"),max_digits=12)),
                ("rate",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=12)),
                ("amount",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=12)),
                ("source_type",models.CharField(blank=True,max_length=60)),
                ("source_id",models.CharField(blank=True,max_length=120)),
                ("source_key",models.CharField(blank=True,max_length=180)),
                ("metadata",models.JSONField(blank=True,default=dict)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("payslip",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="line_items",to="payroll.payslip")),
            ],
            options={"ordering":["kind","code"]},
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("adjustment_type",models.CharField(default="earning",max_length=30)),
                ("code",models.CharField(default="MANUAL",max_length=60)),
                ("description",models.CharField(max_length=180)),
                ("amount",models.DecimalField(decimal_places=2,max_digits=12)),
                ("reason",models.TextField(blank=True)),
                ("status",models.CharField(default="Pending",max_length=30)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_payroll_adjustments",to=settings.AUTH_USER_MODEL)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("payslip",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="adjustments",to="payroll.payslip")),
            ],
            options={"ordering":["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                ("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("payment_date",models.DateField()),
                ("amount",models.DecimalField(decimal_places=2,max_digits=12)),
                ("method",models.CharField(default="Bank Transfer",max_length=40)),
                ("reference",models.CharField(blank=True,max_length=120)),
                ("status",models.CharField(default="Successful",max_length=30)),
                ("remarks",models.TextField(blank=True)),
                ("branch",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="branches.branch")),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="companies.company")),
                ("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="salary_payments",to="employees.employee")),
                ("payslip",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="salary_payments",to="payroll.payslip")),
                ("recorded_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="recorded_salary_payments",to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-payment_date","-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="payrollpolicy",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=True),fields=("company","name"),name="unique_company_payroll_policy"),
        ),
        migrations.AddConstraint(
            model_name="payrollpolicy",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=False),fields=("company","branch","name"),name="unique_branch_payroll_policy"),
        ),
        migrations.AddConstraint(
            model_name="employeecompensationplan",
            constraint=models.UniqueConstraint(fields=("employee","effective_from"),name="unique_employee_compensation_effective_date"),
        ),
        migrations.AddConstraint(
            model_name="compensationcomponent",
            constraint=models.UniqueConstraint(fields=("plan","code"),name="unique_compensation_component_code"),
        ),
        migrations.AddConstraint(
            model_name="jobcardemployeeassignment",
            constraint=models.UniqueConstraint(fields=("job","employee"),name="unique_job_employee_assignment"),
        ),
        migrations.AddConstraint(
            model_name="employeecommission",
            constraint=models.UniqueConstraint(fields=("company","source_key"),name="unique_employee_commission_source"),
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=True),fields=("company","month","year"),name="unique_company_payroll_period"),
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=False),fields=("company","branch","month","year"),name="unique_branch_payroll_period"),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=True),fields=("company","month","year"),name="unique_payroll_run_company_period"),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(condition=models.Q(branch__isnull=False),fields=("company","branch","month","year"),name="unique_payroll_run_branch_period"),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(fields=("payroll_run","employee"),name="unique_payslip_employee_run"),
        ),
        migrations.AddConstraint(
            model_name="payrolllineitem",
            constraint=models.UniqueConstraint(condition=~models.Q(source_key=""),fields=("payslip","source_key"),name="unique_payroll_line_source"),
        ),
        migrations.RunPython(backfill_compensation_plans,migrations.RunPython.noop),
    ]
